{{- if .Values.apiServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-api-server
  labels:
    {{- include "platform.apiServer.labels" . | nindent 4 }}
    {{- with .Values.apiServer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.apiServer.metrics.enabled }}
    - port: {{ .Values.apiServer.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "platform.apiServer.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-api-server-headless
  labels:
    {{- include "platform.apiServer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "platform.apiServer.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-frontend
  labels:
    {{- include "platform.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "platform.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
